### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [bwardak/calculator-project-waiheke#2]
# Feedback

## Requirements

- Deployed website
- Github Repo:
  - README.md
  - 15 commits
- Be responsive and built mobile-first, it should work on different screen widths
- Accept a minimum of 2 inputs, perform an operation and return the output.
- DO NOT USE `eval()`
- Code is highly readable (good naming and indented correctly)

### Let's Build

- A working Calculator
- Practice using Git and GitHub flow
- Apply what you are learning.
  - SCSS
  - BEM

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/02-javascript-typescript/calculator-marking-scheme.md)

| Category             | Score     |
| -------------------- | --------- |
| Version Control      | 10 / 10   |
| Site Output          | 40 / 45   |
| Readability          | 20 / 20   |
| Responsiveness       | 10 / 10   |
| Code Knowledge & Use | 20 / 25   |
| Total Score          | 100 / 110 |

#### Positive

- What a project, this has been an obvious success for you! I like that you have found a way to challenge yourself by adding a ton of different features. You have kept on adding to it, this is great.
  - Keep this up, it does make reviewing projects more interesting
- The UI Looks great, it is clean and clear how to interact with it.
  - I love the theme toggle :)

#### Constructive

- Your BEM is a little hit-and-miss. Sometimes you are following it but other times you are not. Ideally in a project, you have a convention to make sure you have consistency throughout the project.
  - I am going to refactor your HTML slightly to match how you have started to group it.

```html
<!-- calculator IS A BLOCK -->
<div class="calculator calculator--grid">
  <!-- top-screen IS A BLOCK -->
  <div class="top-screen">
    <!-- ITEMS INSIDE ARE ELEMENT SO NAMED BLOCK__ELEMENTS -->
    <div class="top-screen__theme">
      <div class="top-screen__screen top-screen__screen--day"><span class="top-screen__sun">&#127774;</span></div>
      <div class="top-screen__screen top-screen__screen--night"><span class="top-screen__moon">&#127761;</span></div>
    </div>
    <div class="top-screen__screen top-screen__screen--equation">0</div>
    <div class="top-screen__screen top-screen__screen--answer"></div>
    <!-- button CAN BE A BLOCK AS THEY ARE USED ELSEWHERE -->
    <div class="top-screen__screen button--clear">AC</div>
  </div>

  <!-- buttons IS A BLOCK -->
  <div class="buttons">
    <div class="buttons__row buttons__row--first">
      <button class="button button--number">(</button>
      <button class="button button--number">)</button>
      <button class="button button--squared">²</button>
      <button class="button button--operator button--division">/</button>
    </div>

    <div class="buttons__row buttons__row--second">
      <button class="button button--number">7</button>
      <button class="button button--number">8</button>
      <button class="button button--number">9</button>
      <button class="button button--operator button--multiply">*</button>
    </div>

    <div class="buttons__row buttons__row--third">
      <button class="button button--number">4</button>
      <button class="button button--number">5</button>
      <button class="button button--number">6</button>
      <button class="button button--operator button--subtract" id="hide-plus">+-</button>
    </div>

    <div class="buttons__row buttons__row--fourth">
      <button class="button button--number">1</button>
      <button class="button button--number">2</button>
      <button class="button button--number">3</button>
      <button class="button button--operator button--add">+</button>
    </div>

    <div class="buttons__row buttons__row--fifth">
      <button class="button button--ans">ans</button>
      <button class="button button--number">0</button>
      <button class="button button--number">.</button>
      <button class="button--omit button--equals">=</button>
    </div>
  </div>
</div>
```

- When you style you want to use your blocks as a way of styling those specific elements. You do not want to nest your styles too deeply it should only be block > element > modifier.
- With the BEM class names from the HTML above your styles would look like the following.

```scss
.calculator {
  max-width: 280px;
  max-height: 566px;
  width: 100%;
  border: 2px solid $black-color;
  border-radius: 10px;
  background-color: $calculator-color;
  box-shadow: 2px 2px 0 2px $black-color;
  text-align: center;
}

.top-screen {
  background-color: $white-color;
  border-radius: 10px;
  border-bottom: 2px solid $black-color;

  &__screen {
    font: 700 1.5rem $screen-font;
    height: 50px;
  }
}

.buttons {
  background-color: $calculator-color;
}

.button {
  font: 700 1.5rem $screen-font;
  height: 50px;
}

@media screen and (min-width: 768px) {
  .calculator {
    max-width: 350px;
    max-height: 700px;
    width: 100%;
    height: 700px;
  }

  .top-screen {
    &__screen {
      font-size: 1.7rem;
    }

    &__sun,
    &__moon {
      font-size: 40px;
    }
  }

  .buttons {
    &__row {
      height: 77px;
    }
  }

  .button {
    height: 70px;
    width: 70px;
    font-size: 1.7rem;

    &--omit {
      height: 70px;
      width: 70px;
    }
  }
}

@media screen and (min-width: 1024px) {
  .calculator {
    max-width: 450px;
    max-height: 800px;
    width: 100%;
    height: 800px;
  }

  .top-screen {
    &__screen {
      font-size: 2rem;
    }

    &__sun,
    &__moon {
      font-size: 50px;
    }
  }

  .buttons {
    &__row {
      height: 97px;
    }
  }

  .button {
    height: 90px;
    width: 90px;

    &--omit {
      height: 90px;
      width: 90px;
      font-size: 2rem;
    }
  }
}
```

#### Positive

- There are a lot of positives in your TypeScript, as I said it has been a successful project for you.
- I am so glad you separated and grouped your functionality into specific functions. They are named well and each has a clear responsibility, making the codebase easier to understand.
- I can see a solid understanding of some of the concepts we have covered so far.
  - You are interacting with the DOM. Displaying and updating values, acting on different events & using logic to get your calculations on the page. :)
  - You have the core functionality down and have started looking into the edge cases and additional functionality which is a good place to be.
- All in all a great project.

#### Constructive

- With Arrays if you want to clear out the contents you can set the length to 0. This means you do not have to use a loop combined with the `.pop` method in your `handleResetCalculator` function.
  - Good use of loops but there is a simpler way to do it :).

```typescript
const handleResetCalculator = (): void => {
  if (screenAnswer) {
    screenAnswer.innerText = "";
  }
  screenEquation.innerText = "0";
  storingNumbers.length = 0;
  sumOfNumsString.length = 0;
  storingOperators.length = 0;
};
```

- Avoid using `unknown[]` this helps maintain strong type safety and provides the guarantees given by types.

  - The variable name has string in it so I am going to assume it will only contain strings.

  - `const sumOfNumsString: unknown[] = [];` -> `const sumOfNumsString: string[] = [];`

- Try and avoid multiple `||` in if statements as they become harder to read and maintain.
  - I think having 4 is probably right on the limit. `sumOfNumsString[0] === "+" || sumOfNumsString[0] === "+-" || sumOfNumsString[0] === "*" || sumOfNumsString[0] === "/" `
  - You can use an array and the `.includes` method as an alternative and store the result as a variable to improve readability.

```typescript
const handleClickedButtonNumberToArray = (event: Event) => {
  const value = event.currentTarget as HTMLButtonElement;
  sumOfNumsString.push(value.innerText);
  const firstElementIsOperator = ["+", "+-", "*", "/"].includes(sumOfNumsString[0]);
  if (firstElementIsOperator) {
    sumOfNumsString.shift(); // If first entry in array is operator, remove it.
  }
};
```

---
